CREATE TABLE IF NOT EXISTS directions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS services (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS domaines (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS profils_si (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    direction_id INT NULL,
    date_created TIMESTAMP NULL,
    date_updated TIMESTAMP NULL,
    CONSTRAINT fk_profils_si_direction FOREIGN KEY (direction_id) REFERENCES directions (id)
);

CREATE TABLE IF NOT EXISTS ressource_si (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categorie_id INT NOT NULL,
    name VARCHAR(128) NOT NULL,
    type_acces VARCHAR(32) NOT NULL,
    CONSTRAINT fk_ressource_si_categorie FOREIGN KEY (categorie_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS applications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    direction_id INT NULL,
    description VARCHAR(255) NULL,
    date_created TIMESTAMP NULL,
    CONSTRAINT fk_applications_direction FOREIGN KEY (direction_id) REFERENCES directions (id)
);

CREATE TABLE IF NOT EXISTS profil_app (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    application_id INT NOT NULL,
    date_created TIMESTAMP NULL,
    date_updated TIMESTAMP NULL,
    CONSTRAINT fk_profil_app_application FOREIGN KEY (application_id) REFERENCES applications (id),
    CONSTRAINT uk_profil_app_name_application UNIQUE (name, application_id)
);

CREATE TABLE IF NOT EXISTS ressource_app (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INT NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(255) NULL,
    CONSTRAINT fk_ressource_app_application FOREIGN KEY (application_id) REFERENCES applications (id),
    CONSTRAINT uk_ressource_app_name_application UNIQUE (name, application_id)
);

CREATE TABLE IF NOT EXISTS emplois (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emploi_name VARCHAR(128) NOT NULL,
    direction_id INT NOT NULL,
    service_id INT NULL,
    domaine_id INT NULL,
    status VARCHAR(64) NOT NULL,
    profil_si_id INT NULL,
    date_created TIMESTAMP NULL,
    date_updated TIMESTAMP NULL,
    CONSTRAINT fk_emplois_direction FOREIGN KEY (direction_id) REFERENCES directions (id),
    CONSTRAINT fk_emplois_service FOREIGN KEY (service_id) REFERENCES services (id),
    CONSTRAINT fk_emplois_domaine FOREIGN KEY (domaine_id) REFERENCES domaines (id),
    CONSTRAINT fk_emplois_profil_si FOREIGN KEY (profil_si_id) REFERENCES profils_si (id)
);

CREATE TABLE IF NOT EXISTS direction_ressources_default (
    direction_id INT NOT NULL,
    ressource_id INT NOT NULL,
    CONSTRAINT pk_direction_ressources_default PRIMARY KEY (direction_id, ressource_id),
    CONSTRAINT fk_drd_direction FOREIGN KEY (direction_id) REFERENCES directions (id),
    CONSTRAINT fk_drd_ressource FOREIGN KEY (ressource_id) REFERENCES ressource_si (id)
);

CREATE TABLE IF NOT EXISTS profil_si_ressources (
    profil_si_id INT NOT NULL,
    ressource_id INT NOT NULL,
    type_acces VARCHAR(32) NOT NULL,
    CONSTRAINT pk_profil_si_ressources PRIMARY KEY (profil_si_id, ressource_id),
    CONSTRAINT fk_psr_profil_si FOREIGN KEY (profil_si_id) REFERENCES profils_si (id),
    CONSTRAINT fk_psr_ressource FOREIGN KEY (ressource_id) REFERENCES ressource_si (id)
);

CREATE TABLE IF NOT EXISTS profil_app_profil_si (
    profil_app_id INT NOT NULL,
    profil_si_id INT NOT NULL,
    application_id INT NOT NULL,
    CONSTRAINT pk_profil_app_profil_si PRIMARY KEY (profil_app_id, profil_si_id),
    CONSTRAINT uk_paps_application_profil_si UNIQUE (application_id, profil_si_id),
    CONSTRAINT fk_paps_profil_app FOREIGN KEY (profil_app_id) REFERENCES profil_app (id),
    CONSTRAINT fk_paps_profil_si FOREIGN KEY (profil_si_id) REFERENCES profils_si (id),
    CONSTRAINT fk_paps_application FOREIGN KEY (application_id) REFERENCES applications (id)
);

CREATE TABLE IF NOT EXISTS profil_app_ressources (
    profil_app_id INT NOT NULL,
    ressource_app_id INT NOT NULL,
    CONSTRAINT pk_profil_app_ressources PRIMARY KEY (
        profil_app_id,
        ressource_app_id
    ),
    CONSTRAINT fk_par_profil_app FOREIGN KEY (profil_app_id) REFERENCES profil_app (id),
    CONSTRAINT fk_par_ressource_app FOREIGN KEY (ressource_app_id) REFERENCES ressource_app (id)
);